on:
  workflow_dispatch
jobs:  
  expressions:
    runs-on: ubuntu-latest
    steps:
    - name: Run a doployment script
      run: ./deploy/sh
    - name: Cleanup on failure
      run: echo "Deployment succeeded"
      if: success()
